### ISSUE TITLE
How can we get same dataset?

### ISSUE THREAD

**Issue by koba-84** [bayrameda/MrAP#1]
Hello, I tried to reproduce this research, but I’m finding discrepancies in the values 
when building the dataset from the provided link. 

For example, the paper states that the count of "date_of_birth" entries in fb15k-237 is 4406, 
but in FB15K_NumericalTriples.txt, I found 4428 entries. 

Could you clarify what preprocessing steps were applied?

**Comment by bayrameda** [comment]
In fb15k-237, as seen by the number of entities and edges (triples), a subset of it used. First the entities are downgraded to the set possessing one of the top 11 numerical attributes. Then the KG is downgraded to the triples between them. The same process applies to YAGO, with its own numerical attribute set. The final splits used for FB15K is added to the repo. Thanks for your interest.

**Comment by koba-84** [comment]
Thank you very much for your prompt response and for clarifying the preprocessing steps. This information is incredibly helpful, and I appreciate the details on how the dataset was constructed. I’ll proceed with these insights in mind. Thanks again for your support!
